import axios from "axios";

const API_ENDPOINT = "https://www.googleapis.com/youtube/v3/playlists";

const DESCRIPTION = "This playlist is generated by Youtube Playlist Generator";

const createNewPlayList = async (title: string, accessToken: string) => {
  console.log(title);
  console.log(accessToken);
  await axios.post(
    `${API_ENDPOINT}?access_token=${accessToken}&part=snippet,status&resource.snippet.title=${title}&resource.snippet.description=${DESCRIPTION}`
  );
};

export { createNewPlayList };
