import { rest } from "msw";

const videoId = ["1EgiO-RyMGQ", "grG41kS4MUA", "HmKgFJGn46Q"];
const DUMMYPLAYLIST = {
  kind: "youtube#playlist",
  etag: "RRTaTkahgyJiGySg-HRR7IDYPKs",
  id: "PLLWhHQQ2C0UeAaxlXj4XnaRxVZHBIR4rg",
  snippet: {
    publishedAt: "2022-09-07T09:00:31Z",
    channelId: "UCpZXGOA_8z5p6YR5jEzZwCQ",
    title: "a",
    description: "This playlist is generated by Youtube Playlist Generator",
    thumbnails: {
      default: {
        url: "https://i.ytimg.com/img/no_thumbnail.jpg",
        width: 120,
        height: 90,
      },
      medium: {
        url: "https://i.ytimg.com/img/no_thumbnail.jpg",
        width: 320,
        height: 180,
      },
      high: {
        url: "https://i.ytimg.com/img/no_thumbnail.jpg",
        width: 480,
        height: 360,
      },
    },
    channelTitle: "유창헌",
    localized: {
      title: "a",
      description: "This playlist is generated by Youtube Playlist Generator",
    },
  },
  status: {
    privacyStatus: "private",
  },
};

export const handlers = [
  rest.get("/search", (_, res, ctx) => {
    return res(ctx.status(200), ctx.json(videoId));
  }),

  rest.post("/make", (_, res, ctx) => {
    return res(ctx.status(200), ctx.json(DUMMYPLAYLIST));
  }),
];
